apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-monitor-crd
rules:
- apiGroups:
  - helloworld.app
  resources:
  - configmonitor
  - configmonitor/finalizers
  verbs: [ get, list, create, update, delete, deletecollection, watch ]
---
  apiVersion: magalix.com/v1
kind: ConfigMonitor
metadata:
  name: flaskapp-config-monitor
spec:
  configmap: the-map
  podSelector:
    app: frontend