apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configmonitors.helloworld.app
spec:
  scope: Namespaced
  group: helloworld.app
  names:
    kind: ConfigMonitor
    singular: configmonitor
    plural: configmonitors
  versions: 
    - name: v1
      served: true
      storage: true     
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                configMap:
                  type: string
                  description: "Name of the ConfigMap to watch for changes"
                podSelector:
                  type: object
                  description: "Label selector used for selecting Pods"
                  additionalProperties:
                    type: string