apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
commonLabels:
      app: helloworld
      env: prod
resources:
- ../../base

patches:
- path: configmap-prod.yaml
- path: http-route-prod.yaml
